RunMain9: M9c M9l M9r

M9c:
	g++ -O3 -c main/main9.cpp cppfunk/penningtrapclasses.cpp

M9l:
	g++ -O3 main9.o penningtrapclasses.o -o main9.exe -larmadillo

M9r:
	./main9.exe

RunMain10: M10c M10l M10r

M10c:
	g++ -O3 -c main/main10.cpp cppfunk/penningtrapclasses10.cpp

M10l:
	g++ -O3 main10.o peningtrapclasses10.o -o main10.exe -larmadillo

M10r:
	./main10.exe

RunError: Errc Errl ErrR

Errc:
	g++ -O3 -c main/findingerrors.cpp cppfunk/penningtrapclasses.cpp

Errl:
	g++ findingerrors.o penningtrapclasses.o -o err.exe -larmadillo

ErrR:
	./err.exe

ColTrap: CTc CTl CTr

CTc:
	g++ -O3 -c main/mainCloumbTrapped.cpp cppfunk/penningtrapclasses10.cpp

CTl:
	g++ mainCloumbTrapped.o penningtrapclasses10.o -o CT.exe -larmadillo

CTr:
	./CT.exe
