import numpy as np
import matplotlib.pyplot as plt

t, x1, y1, z1, x2, y2, z2=np.loadtxt("../Txtfiler/r2noint.txt", unpack=True)
t, vx1, vy1, vz1, vx2, vy2, vz2=np.loadtxt("../Txtfiler/v2noint.txt", unpack=True)

plt.title("Faseplot i x-retnig uten partikkelkraft for partikkel 1")
plt.plot(x1, vx1)
plt.xlabel("x")
plt.ylabel("vx")
plt.savefig("xnoint1.pdf")
plt.show()
pl t.title("Faseplot i y-retnig uten partikkelkraft for parikkel 1")
plt.plot(y1, vy1)
plt.xlabel("y")
plt.ylabel("vy")
plt.ylabel("vx")
plt.savefig("ynoint1.pdf")
plt.show()
plt.title("Faseplot i z-retnig uten partikkelkraft for parikkel 1")
plt.plot(z1, vz1)
plt.xlabel("z")
plt.ylabel("vz")
plt.savefig("znoint1.pdf")
plt.show()
plt.title("Faseplot i x-retnig uten partikkelkraft for partikkel 2")
plt.plot(x2, vx2)
plt.xlabel("x")
plt.ylabel("vx")
plt.savefig("xnoint2.pdf")
plt.show()
plt.title("Faseplot i y-retnig uten partikkelkraft for parikkel 2")
plt.plot(y2, vy2)
plt.xlabel("y")
plt.ylabel("vy")
plt.ylabel("vx")
plt.savefig("ynoint2.pdf")
plt.show()
plt.title("Faseplot i z-retnig uten partikkelkraft for parikkel 2")
plt.plot(z2, vz2)
plt.xlabel("z")
plt.ylabel("vz")
plt.savefig("znoint2.pdf")
plt.show()
t, x1, y1,z1, x2, y2, z2=np.loadtxt("../Txtfiler/r2int.txt", unpack=True)
t, vx1, vy1, vz1, vx2, vy2, vz2=np.loadtxt("../Txtfiler/v2int.txt", unpack=True)
plt.title("Faseplot i x-retnig med partikkelkraft for partikkel 1")
plt.plot(x1, vx1)
plt.xlabel("x")
plt.ylabel("vx")
plt.savefig("xint1.pdf")
plt.show()
plt.title("Faseplot i y-retnig med partikkelkraft for parikkel 1")
plt.plot(y1, vy1)
plt.xlabel("y")
plt.ylabel("vy")
plt.ylabel("vx")
plt.savefig("yint1.pdf")
plt.show()
plt.title("Faseplot i z-retnig med partikkelkraft for parikkel 1")
plt.plot(z1, vz1)
plt.xlabel("z")
plt.ylabel("vz")
plt.savefig("zint1.pdf")
plt.show()
plt.title("Faseplot i x-retnig med partikkelkraft for partikkel 2")
plt.plot(x2, vx2)
plt.xlabel("x")
plt.ylabel("vx")
plt.savefig("xint2.pdf")
plt.show()
plt.title("Faseplot i y-retnig med partikkelkraft for parikkel 2")
plt.plot(y2, vy2)
plt.xlabel("y")
plt.ylabel("vy")
plt.ylabel("vx")
plt.savefig("yint2.pdf")
plt.show()
plt.title("Faseplot i z-retnig med partikkelkraft for parikkel 2")
plt.plot(z2, vz2)
plt.xlabel("z")
plt.ylabel("vz")
plt.savefig("zint2.pdf")
plt.show()
