import numpy as np
import matplotlib.pyplot as plt

t, x1, y1, z1, x2, y2, z2=np.loadtxt("../Txtfiler/r2noint.txt", unpack=True)
t, vx1, vy1, vz1, vx2, vy2, vz2=np.loadtxt("../Txtfiler/v2noint.txt", unpack=True)
plt.suptitle("Fasediagram uten partikkelkraft")
plt.subplot(1,3,1)
plt.plot(x1, vx1)
plt.xlabel("x")
plt.ylabel("vx")
plt.subplot(1,3,2)
plt.plot(y1, vy1)
plt.xlabel("y")
plt.ylabel("vy")
plt.subplot(1,3,3)
plt.plot(z1, vz1)
plt.xlabel("z")
plt.ylabel("vz")
plt.savefig("Fasenoint.pdf")
plt.show()
t, x1, y1,z1, x2, y2, z2=np.loadtxt("../Txtfiler/r2int.txt", unpack=True)
t, vx1, vy1, vz1, vx2, vy2, vz2=np.loadtxt("../Txtfiler/v2int.txt", unpack=True)
plt.suptitle("Fasediagram med partikkelkraft")
plt.subplot(1,3,1)
plt.plot(x1, vx1)
plt.xlabel("x")
plt.ylabel("vx")
plt.subplot(1,3,2)
plt.plot(y1, vy1)
plt.xlabel("y")
plt.ylabel("vy")
plt.subplot(1,3,3)
plt.plot(z1, vz1)
plt.xlabel("z")
plt.ylabel("vz")
plt.savefig("Faseint.pdf")
plt.show()
