import numpy as np
import matplotlib.pyplot as plt
t, x1, y1,z1, x2, y2, z2=np.loadtxt("../Txtfiler/r2noint.txt", unpack=True)
plt.title("To partikler i feltet uten partikkelkraft")
plt.plot(x1,y1, label="Partikkel 1")
plt.plot(x2, y2, label="Partikkel 2")
plt.xlabel("x-posisjon i mikrometer")
plt.ylabel("y-posisjon i mikrometer")
plt.axis("equal")
plt.legend()
plt.savefig("xypartnoint.pdf")
plt.show()
t, x1, y1, z1 , x2, y2, z2=np.loadtxt("../Txtfiler/r2int.txt", unpack=True)
plt.title("To partikler i feltet med partikkelkraft")
plt.plot(x1,y1, label="Partikkel 1")
plt.plot(x2, y2, label="Partikkel 2")
plt.xlabel("x-posisjon i mikrometer")
plt.ylabel("y-posisjon i mikrometer")
plt.axis("equal")
plt.legend()
plt.savefig("xypartint.pdf")
plt.show()
